name: Java CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, Test & Package
        run: mvn verify

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-jar
          path: target/app.jar

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: springboot-jar

      - name: Copy JAR to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "app.jar"
          target: "/app/ACS/apache-tomcat-10.1.50/webapps/cicd/"

      - name: Restart Application
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /app/ACS/apache-tomcat-10.1.50/webapps/cicd
            pkill -f 'app.jar' || true
            sleep 2
            nohup java -jar app.jar > app.log 2>&1 &
